#!/usr/bin/env python3
"""Every relative link in a tracked Markdown file must open on GitHub.

GitHub renders the repository as it is, so a link is valid only if it resolves, relative to the file it
is in, to a tracked file or folder. A link to something that exists only on the built site
(docs/learn/<chapter>/, generated by tools/sync_course.py) is a 404 on GitHub. The site build rewrites
these GitHub links to site pages (tools/mkdocs_links.py), so authors always write the GitHub form.
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LINK = re.compile(r"!?\[[^\]]*\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")
CODE = re.compile(r"```.*?```|`[^`\n]*`", re.S)


def tracked() -> set:
    out = subprocess.run(["git", "-C", str(ROOT), "ls-files"], capture_output=True, text=True, check=True).stdout
    files = set(out.split())
    return files | _all_parents(files)


def _all_parents(files: set) -> set:
    dirs = set()
    for f in files:
        p = Path(f).parent
        while str(p) != ".":
            dirs.add(p.as_posix())
            p = p.parent
    return dirs


def main() -> int:
    known = tracked()
    errors = []
    for md in sorted(f for f in known if f.endswith(".md")):
        text = CODE.sub("", (ROOT / md).read_text())
        for target in LINK.findall(text):
            if re.match(r"^[a-z][a-z0-9+.-]*:", target) or target.startswith("#"):
                continue                                         # URL, mailto:, in-page anchor
            path = target.split("#")[0].split("?")[0]
            resolved = (ROOT / md).parent.joinpath(path).resolve()
            try:
                rel = resolved.relative_to(ROOT).as_posix()
            except ValueError:
                errors.append(f"{md}: link '{target}' leaves the repository")
                continue
            if rel not in known and rel != ".":
                errors.append(f"{md}: link '{target}' -> {rel} is not a tracked file (404 on GitHub)")
    if errors:
        print(f"check_links: {len(errors)} broken link(s)")
        for e in errors:
            print("  -", e)
        return 1
    print("check_links: OK (every relative link opens on GitHub)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
